### PR TITLE
PlotlyImage Widget

### LINKED ISSUE #17: windowing of images

### LINKED ISSUE #18: zoom feature of images

### LINKED ISSUE #26: Disable answer buttons while loading
Related to #16 we should maybe remove/lock the Yes/No buttons while an image is loading.

### LINKED ISSUE #42: track user interactions
adding google analytics lets us see most of the browser / client information #22  but is very limited on interaction since it focuses more on userflow through multiple pages. 
The SPA solution would be to use: ```ga('set', 'page', '/new-page.html'); ga('send', 'pageview');```) but I am not sure how much that helps us.

### PR DESCRIPTION
**Pull request by kmader**
adding a plotly based viewer (supports zoom)

https://mybinder.org/v2/gh/chestrays/jupyanno/plotly-viewer?urlpath=%2Fmuapps%2Frandom_githubber%2Fanno_app.ipynb

Fixes #17 
Fixes #18 
Fixes #26 
Fixes #42 

image

### CODE REVIEW

**Comment by betatim** [comment]
screen shot 2018-08-16 at 08 46 55

Is what I get when I follow the link in the top comment :-/

**Comment by kmader** [comment]
It's what I get too, the second image looks fine though. I need a deeper dig into plotlys api

**Comment by kmader** [comment]
unfortunately the 50 line snippet doesnt seem to work :( the mouseover works but nothing actually moves
```
ipw.HTML("""
<script>
function simple_zoom(e){
  var zoomer = e.currentTarget;
  e.offsetX ? offsetX = e.offsetX : offsetX = e.touches[0].pageX
  e.offsetY ? offsetY = e.offsetY : offsetX = e.touches[0].pageX
  x = offsetX/zoomer.offsetWidth*100
  y = offsetY/zoomer.offsetHeight*100
  zoomer.style.backgroundPosition = x + '% ' + y + '%';
}
</script>
<style>
figure.zoom {
  background-position: 50% 50%;
  position: relative;
  width: 500px;
  overflow: hidden;
  cursor: zoom-in;
}
figure.zoom img:hover {
  opacity: 0;
}
figure.zoom img {
  transition: opacity .5s;
  display: block;
  width: 100%;
}

</style>
<figure class="zoom" onmousemove="simple_zoom(event)" style="background-image: url(//res.cloudinary.com/active-bridge/image/upload/slide1.jpg)">
  <img src="//res.cloudinary.com/active-bridge/image/upload/slide1.jpg" />
</figure>
""")
```

**Comment by kmader** [comment]
@betatim should work now

**Comment by kmader** [comment]
urgh, zooming to the wrong region

ezgif com-video-to-gif

**Pull request merged**
