### PR TITLE
Add dependencies

### PR DESCRIPTION
**Pull request by betatim**
A few missing dependencies in the `setup.py`. Noticed because I did `pip install -e.` in a new env and was expecting it to work.

### CODE REVIEW

**Comment by kmader** [comment]
ahh one of the notebooks is failing, that is almost certainly not due to your changes though

**Comment by betatim** [comment]
They are missing the plotly library, looking into it.

**Comment by kmader** [comment]
the missing plotly or missing seaborn happens rather frequently (1 of 5 builds or so), is there a way to get around this?

**Comment by betatim** [comment]
That seems high, for other projects we installing miniconda works reliably, but is slow :-/

**Pull request merged**
